language: node_js
node_js:
  - 8
before_script:
  - npm install -g gulp-cli
services: mongodb
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
script:
  - gulp test
notifications:
  email:
    recipients:
    - humatios@hotmail.com
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - develop
  - test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
