version: '2'

services:
  web:
    command: gulp serve
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/qrveytoggl-dev

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
